add-highlighter global/ number-lines -relative -hlcursor
add-highlighter global/ wrap
add-highlighter global/ show-matching

set-option global tabstop 2
set-option global indentwidth 2
set global disabled_hooks .*-indent

colorscheme one-darker

define-command -docstring "vsplit [<commands>]: split tmux vertically" \
vsplit -params .. -command-completion %{
  tmux-terminal-horizontal kak -c %val{session} -e "%arg{@}"
}

define-command -docstring "hsplit [<commands>]: split tmux horizontally" \
hsplit -params .. -command-completion %{
  tmux-terminal-vertical kak -c %val{session} -e "%arg{@}"
}

define-command -docstring "tabnew [<commands>]: create new tmux window" \
tabnew -params .. -command-completion %{
  tmux-terminal-window kak -c %val{session} -e "%arg{@}"
}
